[phases.setup]
nixPkgs = ["...", "playwright-driver", "chromium"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.deploy]
# Kita tidak perlu install-deps lagi karena sudah dihandle Nix
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"